### ISSUE TITLE
In some modded biomes, SeasonHUD displays incorrectly.

### ISSUE THREAD

**Issue by zlainsama** [lanAnderson/SeasonHUD#7]
![image](https://user-images.githubusercontent.com/3251859/216617866-92c8c1cc-54af-4986-817d-dd7c24136807.png)
![image](https://user-images.githubusercontent.com/3251859/216617924-971cec29-8a62-4a4e-9012-6a83959d040c.png)
![image](https://user-images.githubusercontent.com/3251859/216617953-4d1ff847-6c41-40e8-8263-32368aa18841.png)
![image](https://user-images.githubusercontent.com/3251859/216617995-aeec9269-d8e2-40eb-9b9f-acf980cbf20e.png)

First two are in this mod: [Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.13](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go/files/4027228)
Last two are in this mod: [WWOO-FORGE-3.1.9+1.19.x](https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld/files/4127875)
I'm not sure if this happens in other biomes.
I also had this mod installed, not sure if it has influence: [sereneseasonfix-1.19.2-1.0.7](https://www.curseforge.com/minecraft/mc-mods/serene-seasons-fix/files/4329248)

**Comment by lanAnderson** [comment]
The change to "Mid Wet" is the intended behavior, as the current biome is classified as "Tropical" by SereneSeasons.  The Tropical seasons don't follow the normal season behavior, but instead are classified as "Wet" or "Dry", each being 48 days long and split between 3 sub-season (Early, Mid, Late).

The "Tropical" season is determined by the biome's (vanilla) temperature value. Anything greater than "0.8" is considered tropical by SereneSeasons (in vanilla, this would be biomes like Jungles, Mushroom Islands, Deserts, Savannas, etc. ). I took a look at the WWOO biomes and they seem to set the temperature values for the Jungle/Rainforests to "0.7" instead of the vanilla "0.95", so SereneSeasons doesn't consider them Tropical. 

In the folder for your world, there is a "sereneseasons-server.toml" file in the serverconfig folder. That has a setting called "tropical_biomes" that will let you manually have a biome classified as Tropical, if you want consistency between the biomes.

**Comment by zlainsama** [comment]
Thanks for the info, I didn't know that.
Could you add an option to show normal season info regardless of the Tropical biomes?

**Comment by lanAnderson** [comment]
Yup I can do that, should be easy enough

**Comment by lanAnderson** [comment]
Should be good to go with v1.4.3 that is uploading to CurseForge now
